### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by xanthipe** [bathlarp/frontend#14]
Build a basic styled button component including an optional icon and primary/secondary switching.

**Comment by DiracLotus** [comment]
Might look to pick this up imminently if that's okay?

**Comment by xanthipe** [comment]
Go for it :) We have a couple of designs on the Figma already (https://www.figma.com/file/QcjBY56Dql5WNfVycHoWJL/BladesDB2?type=design&node-id=221-97&mode=design&t=Dq0ZkCDxZt07iGzy-4), add to it as needed.
